# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppfunique <- function(mat, tol) {
    .Call('_destim_cppfunique', PACKAGE = 'destim', mat, tol)
}

cppfuniqueind <- function(mat, tol) {
    .Call('_destim_cppfuniqueind', PACKAGE = 'destim', mat, tol)
}

