#' @title Reads the number of individuals detected by network at initial time.
#'
#' @description Reads the number of individuals detected by network at initial time instant, as they are generated by
#'   the \code{aggregation} package.
#'
#' @param nnetFileName The file name of the random values generated by the \code{aggregation} package for the number of
#'   individuals detected by network for each region and each time instant.
#'
#' @return A data.table object with two columns: \code{region, N} 
#'
#'
#' @import data.table
#'
#' @export
readNnetInitial <- function(nnetFileName) {
    
    if (!file.exists(nnetFileName))
        stop(paste0(nnetFileName, " does not exists!"))
    
    nNet <- fread(
        nnetFileName,
        sep = ',',
        header = TRUE,
        stringsAsFactors = FALSE
    )
    
    nNet<-nNet[time==0][,iter:=NULL][,time:=NULL]
    return (nNet)    
}